### ISSUE TITLE
菜单全部重复了一遍，隐藏在滚动条下面，向下一翻就看到重复的菜单了

### ISSUE THREAD

**Issue by yany88** [canbez/dcat-theme#1]
如下图所示：
系统：centos
php版本：8.0.7
laravel版本：8.78.1
dcat-admin版本：2.1.7-beta
![image](https://user-images.githubusercontent.com/9587112/149091276-a6942a2b-029e-47ce-8e2a-ee4f469183b3.png)

**Comment by ly2ang** [comment]
我这边没有复现你这边的问题。
1.你可以看一下是不是样式覆盖重复了。
2.你可以把 admin_menu 这个表sql 导出发我邮箱，我这边测试一下
![image](https://user-images.githubusercontent.com/37921490/149093515-fb638ca2-ba0f-4ab2-916e-dc767f77cf1d.png)

**Comment by liaoshengping** [comment]
我的也会

![image](https://user-images.githubusercontent.com/24541157/154902347-64f83230-5ded-43a9-8aef-27367f533653.png)

**Comment by ly2ang** [comment]
> 我的也会
> 
> ![image](https://user-images.githubusercontent.com/24541157/154902347-64f83230-5ded-43a9-8aef-27367f533653.png)

目前菜单就正常的设置应该是没有问题的，我自己也有在用，如果可以，提供一下menu菜单的父子关系，我这边可以复现一下

**Comment by lovemintblue** [comment]
这个问题貌似还在啊
